name: my_flutter_project
description: "A new MyFlutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^12.1.1
  equatable: ^2.0.5
  intl: ^0.18.1
  fl_chart: ^0.65.0
  shared_preferences: ^2.2.2

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true